name: ContainerPOC
on:
  workflow_call:
    inputs:
      docker_image:
        required: true
        description: the image to ubuntu-latest
        type: string
        #default: node:14.16


jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.docker_image }}
    steps:
      - uses: actions/checkout@v3
      - name: Check for dockerenv file
        run: ps aux